/**
 * RLM v2 integration: async scripted `BaseLM`, `search` / `summarise` over
 * chunked context, trace tag order vs AST. Deeper effect-loop and memory
 * cases live in `rlm_effects.test.ts` / sections below.
 */

import { afterEach, describe, expect, it } from 'vitest';

import type { Message } from '../src/chat_message.js';
import { createField } from '../src/field.js';
import { BaseLM, type LMOutput } from '../src/lm.js';
import { RLM } from '../src/rlm.js';
import { settings } from '../src/settings.js';
import { createSignature } from '../src/signature.js';
import type { EffectHandler } from '../src/rlm_types.js';
import type { MemorySchema } from '../src/rlm_memory.js';
import type { StaticPlan } from '../src/rlm_task_router.js';
import { oracle, vref } from '../src/rlm_combinators.js';

// ---------------------------------------------------------------------------
// Async scripted LM
// ---------------------------------------------------------------------------

/**
 * Minimal `BaseLM` that returns a single canned JSON completion per
 * call, asynchronously. The `async generate` hook is awaited by the
 * base class; every call yields to the microtask queue so the facade's
 * async graph is visibly non-synchronous.
 *
 * Scripting strategy: keyed by the `task_type_hint` substring embedded
 * in the first user message. The classifier and the oracle both hit
 * the same LM, but their prompts are distinguishable (classifier sees
 * the literal string `"Classify"` in its signature instructions;
 * oracle sees the `prompt` field we build per chunk). The keying keeps
 * the test readable and deterministic without a stateful call counter.
 */
class ScriptedAsyncLM extends BaseLM {
  readonly calls: Array<{
    readonly role: 'classifier' | 'oracle' | 'other';
    readonly content: string;
  }> = [];
  readonly classifierPayload: string;
  readonly oracleResponses: Map<string, string>;
  readonly defaultOracle: string;
  readonly verifierVerdicts: Map<string, boolean>;

  constructor(options: {
    readonly classifierPayload: string;
    readonly oracleResponses: Record<string, string>;
    readonly defaultOracle: string;
    readonly verifierVerdicts?: Record<string, boolean>;
  }) {
    super({ model: 'scripted-async' });
    this.classifierPayload = options.classifierPayload;
    this.oracleResponses = new Map(Object.entries(options.oracleResponses));
    this.defaultOracle = options.defaultOracle;
    this.verifierVerdicts = new Map(
      Object.entries(options.verifierVerdicts ?? {}),
    );
  }

  protected override async agenerate(
    _prompt?: string,
    messages?: readonly Message[],
    _kwargs?: Record<string, unknown>,
  ): Promise<readonly LMOutput[]> {
    await Promise.resolve();
    const userContent = extractUserContent(messages);
    const allContent = allMessageContent(messages);
    // The classifier signature's instructions include the literal
    // phrase "Classify the user request", which appears in the system
    // message the Predict adapter formats. Oracle signatures do not
    // include that phrase — they use the default `Given the fields ...`
    // autogenerated instructions. This keying is adapter-agnostic
    // (ChatAdapter and JSONAdapter both pipe signature.instructions
    // through `formatTaskDescription`).
    const isClassifier = allContent.includes('Classify the user request');
    this.calls.push({
      role: isClassifier ? 'classifier' : 'oracle',
      content: userContent,
    });
    if (isClassifier) {
      return [this.classifierPayload];
    }
    const answer = this.pickOracleAnswer(userContent);
    return [
      formatOracleCompletion(
        allContent,
        userContent,
        answer,
        this.verifierVerdicts,
      ),
    ];
  }

  private pickOracleAnswer(userContent: string): string {
    for (const [needle, response] of this.oracleResponses) {
      if (userContent.includes(needle)) return response;
    }
    return this.defaultOracle;
  }

  get oracleCalls(): readonly { readonly content: string }[] {
    return this.calls.filter((c) => c.role === 'oracle');
  }

  get classifierCalls(): readonly { readonly content: string }[] {
    return this.calls.filter((c) => c.role === 'classifier');
  }
}

function extractUserContent(messages: readonly Message[] | undefined): string {
  if (!messages) return '';
  for (let i = messages.length - 1; i >= 0; i -= 1) {
    const msg = messages[i]!;
    if (msg.role === 'user' && typeof msg.content === 'string') {
      return msg.content;
    }
  }
  return typeof messages[0]?.content === 'string' ? (messages[0].content as string) : '';
}

function allMessageContent(messages: readonly Message[] | undefined): string {
  if (!messages) return '';
  return messages
    .map((m) => {
      if (typeof m.content === 'string') return m.content;
      return m.content
        .map((part) => (part.type === 'text' ? (part.text ?? '') : ''))
        .join('\n');
    })
    .join('\n');
}

/**
 * Serialize an oracle-leaf answer in whichever wire shape the current
 * adapter call expects. The RLM v2 runtime calls the LM through three
 * different oracle signatures depending on the combinator node and the
 * reducer in use:
 *
 * - `EFFECT_ORACLE_SIGNATURE` (`kind`, `value`, `effect_name`,
 *   `effect_args`): direct `oracle` leaves.
 * - `ORACLE_SIGNATURE` (`answer`): each lane of a `vote` combinator
 *   and every model in a `majority`/`verifier` `ensemble`.
 * - `CONFIDENCE_ORACLE_SIGNATURE` (`answer`, `confidence`): each
 *   model in an `ensemble` with reducer `'confidence'`.
 * - `RLM_VERIFIER_SIGNATURE` (`verdict`): verifier probes for both
 *   `vote`'s and `ensemble`'s `'verifier'` reducer and beam selection in `RLM`.
 *
 * The adapter's `Your output fields are: ...` listing in the system
 * message is the canonical way to disambiguate; we scan the message
 * text for the output-field names and pick the matching JSON envelope.
 * The boolean `verdict` case is keyed by `userContent`, which lets the
 * beam-routing test steer the verifier toward a non-primary branch
 * without adding a second LM stub.
 */
function formatOracleCompletion(
  systemAndUserContent: string,
  userContent: string,
  answer: string,
  verifierVerdicts: ReadonlyMap<string, boolean>,
): string {
  if (containsOutputField(systemAndUserContent, 'kind')) {
    return JSON.stringify({
      kind: 'value',
      value: answer,
      effect_name: null,
      effect_args: null,
    });
  }
  if (containsOutputField(systemAndUserContent, 'verdict')) {
    const verdict =
      [...verifierVerdicts.entries()].find(([needle]) =>
        userContent.includes(needle),
      )?.[1] ?? true;
    return JSON.stringify({ verdict });
  }
  if (containsOutputField(systemAndUserContent, 'confidence')) {
    return JSON.stringify({ answer, confidence: 0.5 });
  }
  return JSON.stringify({ answer });
}

/**
 * Match the `- \`<name>\` (` bullet inside the adapter's
 * `Your output fields are:` block. The adapter renders each output
 * field on its own line as `` - `name` (type): description `` (see
 * `describeField` in `src/adapter.ts`), so a literal prefix check is
 * robust to stylistic changes in the rest of the system message.
 */
function containsOutputField(content: string, name: string): boolean {
  const outputsBlockStart = content.indexOf('Your output fields are:');
  if (outputsBlockStart < 0) return false;
  const block = content.slice(outputsBlockStart);
  return block.includes(`- \`${name}\` (`);
}

// ---------------------------------------------------------------------------
// Shared test helpers
// ---------------------------------------------------------------------------

const LONG_CONTEXT = [
  'alpha fact one',
  'beta fact two',
  'gamma fact three with the secret word: owl',
  'delta fact four',
  'epsilon fact five',
  'zeta fact six',
  'eta fact seven',
  'theta fact eight',
  'iota fact nine',
  'kappa fact ten',
]
  .join('. ')
  .repeat(20);

afterEach(() => {
  settings.reset();
});

// ---------------------------------------------------------------------------
// Happy-path cases
// ---------------------------------------------------------------------------

describe('RLM v2 end-to-end', () => {
  it('answers a search-typed question over a chunked context', async () => {
    const lm = new ScriptedAsyncLM({
      classifierPayload: JSON.stringify({
        primary: 'search',
        confidence: 0.95,
        candidates: ['search'],
      }),
      oracleResponses: {
        // The search plan is:
        //   concat(map(fn(chunk, oracle(chunk, 'gpt-fast')), split(input, k)), lit('\n---\n'))
        // Every oracle call sees ONE chunk. Our keying on the chunk
        // text is enough to make the per-chunk responses
        // distinguishable without the test caring about k's exact
        // value (the planner picks it).
        'owl': 'found owl',
      },
      defaultOracle: 'nothing here',
    });
    settings.configure({ lm });

    const rlm = new RLM('question: str, context: str -> answer: str');
    const result = await rlm.aforward({
      question: 'What is the secret word?',
      context: LONG_CONTEXT,
    });

    expect(typeof result.get('answer')).toBe('string');
    expect(result.get('answer')).toContain('found owl');
    expect(lm.classifierCalls.length).toBe(1);
    expect(lm.oracleCalls.length).toBeGreaterThanOrEqual(2);

    const route = result.get('_rlm_route') as {
      readonly kind: string;
      readonly taskTypes: readonly string[];
    };
    expect(route.kind).toBe('single');
    expect(route.taskTypes).toEqual(['search']);
  });

  it('answers a summarise-typed question over a chunked context', async () => {
    const lm = new ScriptedAsyncLM({
      classifierPayload: JSON.stringify({
        primary: 'summarise',
        confidence: 0.9,
        candidates: ['summarise'],
      }),
      oracleResponses: {
        // The summarise plan is:
        //   oracle(concat(map(..., split(input, k)), lit('\n\n')), 'gpt-deep')
        // So there are (k + 1) oracle calls total: `k` per-chunk
        // summaries (each sees the chunk text) + 1 synthesis call that
        // sees the concatenated per-chunk summaries. Key the synthesis
        // response on the "summarized" token we emit from every chunk.
        'summarized': 'final combined summary',
      },
      defaultOracle: 'summarized chunk',
    });
    settings.configure({ lm });

    const rlm = new RLM('article: str -> summary: str');
    const result = await rlm.aforward({
      article: LONG_CONTEXT,
    });

    const summary = result.get('summary');
    expect(summary).toBe('final combined summary');

    const route = result.get('_rlm_route') as {
      readonly kind: string;
      readonly taskTypes: readonly string[];
    };
    expect(route.kind).toBe('single');
    expect(route.taskTypes).toEqual(['summarise']);
    // One synthesis + at least two per-chunk summaries.
    expect(lm.oracleCalls.length).toBeGreaterThanOrEqual(3);
  });

  it('reduces low-confidence beam routes with a verifier instead of always taking the primary branch', async () => {
    const lm = new ScriptedAsyncLM({
      classifierPayload: JSON.stringify({
        primary: 'search',
        confidence: 0.2,
        candidates: ['search', 'aggregate'],
      }),
      oracleResponses: {
        'partial fact': 'aggregate-best',
      },
      defaultOracle: 'partial fact',
      verifierVerdicts: {
        'aggregate-best': true,
        'partial fact': false,
      },
    });
    settings.configure({ lm });

    const rlm = new RLM('question: str, context: str -> answer: str');
    const result = await rlm.aforward({
      question: 'Which route should win?',
      context: LONG_CONTEXT,
    });

    expect(result.get('answer')).toBe('aggregate-best');
    const route = result.get('_rlm_route') as {
      readonly kind: string;
      readonly taskTypes: readonly string[];
      readonly selectedTaskType: string;
    };
    expect(route.kind).toBe('beam');
    expect(route.taskTypes).toEqual(['search', 'aggregate']);
    expect(route.selectedTaskType).toBe('aggregate');
    expect(lm.classifierCalls.length).toBe(1);
    expect(lm.oracleCalls.length).toBeGreaterThanOrEqual(3);
  });

  it('honors an explicit taskType override and skips the classifier', async () => {
    const lm = new ScriptedAsyncLM({
      classifierPayload: 'this payload should never be consumed',
      oracleResponses: {},
      defaultOracle: 'deterministic result',
    });
    settings.configure({ lm });

    const rlm = new RLM('question: str -> answer: str', {
      taskType: 'classify',
      budget: { selfConsistencyN: 3 },
    });
    const result = await rlm.aforward({ question: 'label me' });

    expect(result.get('answer')).toBe('deterministic result');
    expect(lm.classifierCalls.length).toBe(0);
    expect(lm.oracleCalls.length).toBeGreaterThanOrEqual(1);

    const route = result.get('_rlm_route') as { readonly taskTypes: readonly string[] };
    expect(route.taskTypes).toEqual(['classify']);
  });

  it("trace records the plan's AST walk in evaluation order", async () => {
    const lm = new ScriptedAsyncLM({
      classifierPayload: JSON.stringify({
        primary: 'search',
        confidence: 0.99,
        candidates: ['search'],
      }),
      oracleResponses: {},
      defaultOracle: 'chunk result',
    });
    settings.configure({ lm });

    const rlm = new RLM('question: str, context: str -> answer: str');
    const result = await rlm.aforward({
      question: 'q',
      context: LONG_CONTEXT,
    });

    // The search plan resolves to:
    //   concat(map(fn(c, oracle(c, 'gpt-fast')), split(input, k)), lit('\n---\n'))
    // The trace captures the top-level `evaluate` calls in completion
    // order. Deepest nodes complete first (var lookups, oracles,
    // split), then their parents (map), then the root (concat).
    const trace = result.get('_rlm_trace') as readonly {
      readonly nodeTag: string;
      readonly ok: boolean;
    }[];
    expect(trace.length).toBeGreaterThanOrEqual(5);
    expect(trace.every((t) => t.ok)).toBe(true);

    // The outermost (last) node is `concat`: it completes last.
    expect(trace[trace.length - 1]?.nodeTag).toBe('concat');
    // Every oracle tag is present.
    expect(trace.filter((t) => t.nodeTag === 'oracle').length).toBeGreaterThanOrEqual(2);
    // `split` appears exactly once (the search plan splits at the root only).
    expect(trace.filter((t) => t.nodeTag === 'split').length).toBe(1);
    // `map` appears exactly once.
    expect(trace.filter((t) => t.nodeTag === 'map').length).toBe(1);
  });

  it('throws when forward() is called (sync API is intentionally dead)', () => {
    const rlm = new RLM('q: str -> a: str');
    expect(() => rlm.forward({ q: 'x' } as { q: string })).toThrow(
      'async-only',
    );
  });

  it('throws a clear error when no LM is configured', async () => {
    const rlm = new RLM('q: str -> a: str');
    await expect(rlm.aforward({ q: 'x' } as { q: string })).rejects.toThrow(
      /sub-LM|lm/i,
    );
  });

  it('drops trace when trackTrace=false', async () => {
    const lm = new ScriptedAsyncLM({
      classifierPayload: JSON.stringify({
        primary: 'classify',
        confidence: 0.99,
        candidates: ['classify'],
      }),
      oracleResponses: {},
      defaultOracle: 'label-a',
    });
    settings.configure({ lm });

    const rlm = new RLM('question: str -> label: str', {
      trackTrace: false,
    });
    const result = await rlm.aforward({ question: 'q' });

    expect(result.get('label')).toBe('label-a');
    expect(result.has('_rlm_trace')).toBe(false);
    expect(result.has('_rlm_route')).toBe(false);
    expect(result.has('_rlm_classifier')).toBe(false);
  });

  it('honors signature defaults when building the top-level prompt', async () => {
    const signature = createSignature(
      new Map([
        ['question', createField({ kind: 'input', name: 'question' })],
        [
          'context',
          createField({
            kind: 'input',
            name: 'context',
            default: 'default context with owl',
          }),
        ],
      ]),
      new Map([
        ['answer', createField({ kind: 'output', name: 'answer' })],
      ]),
    );
    const lm = new ScriptedAsyncLM({
      classifierPayload: JSON.stringify({
        primary: 'search',
        confidence: 0.99,
        candidates: ['search'],
      }),
      oracleResponses: {
        owl: 'found owl in default context',
      },
      defaultOracle: 'no owl here',
    });
    settings.configure({ lm });

    const rlm = new RLM(signature);
    const result = await rlm.aforward({ question: 'What is the word?' });

    expect(result.get('answer')).toContain('found owl in default context');
  });

  it('populates every declared output field in the returned prediction', async () => {
    const lm = new ScriptedAsyncLM({
      classifierPayload: JSON.stringify({
        primary: 'classify',
        confidence: 0.99,
        candidates: ['classify'],
      }),
      oracleResponses: {},
      defaultOracle: 'label-a',
    });
    settings.configure({ lm });

    const rlm = new RLM('question: str -> answer: str, rationale: str', {
      taskType: 'classify',
    });
    const result = await rlm.aforward({ question: 'q' });

    expect(result.get('answer')).toBe('label-a');
    expect(result.has('rationale')).toBe(true);
    expect(result.get('rationale')).toBeUndefined();
  });

  it('rejects invalid budget and route options at construction time', () => {
    expect(
      () => new RLM('q: str -> a: str', { budget: { maxParallelism: 0 } }),
    ).toThrow(/maxParallelism/i);
    expect(
      () => new RLM('q: str -> a: str', { routeThreshold: 2 }),
    ).toThrow(/routeThreshold/i);
    expect(
      () => new RLM('q: str -> a: str', { routeBeamTopK: 0 }),
    ).toThrow(/routeBeamTopK/i);
  });

  it('dispatches a Search effect through a user-registered handler and resumes with the result', async () => {
    // Scenario: a `pairwise`-typed task (plan is a single top-level
    // `oracle(...)` node, so the effect loop is the oracle leaf's own
    // harness). The LM requests a Search tool on turn 0 and returns a
    // final answer on turn 1 that embeds the handler's result.
    const searchQueries: string[] = [];
    const searchHandler: EffectHandler = {
      name: 'Search',
      async handle(effect) {
        if (effect.kind !== 'Search') {
          return { ok: false, error: 'Search handler: wrong kind' };
        }
        searchQueries.push(effect.query);
        return { ok: true, value: 'needle result for ' + effect.query };
      },
    };

    const lm = new EffectScriptedAsyncLM({
      classifierPayload: JSON.stringify({
        primary: 'pairwise',
        confidence: 0.95,
        candidates: ['pairwise'],
      }),
      // Turn 0 fires when the LM hasn't seen an EFFECT block yet.
      // Turn 1 fires after we've appended a Search result to the prompt.
      initialEffect: { name: 'Search', args: { query: 'needle' } },
      followUpAnswer: 'found: needle result for needle',
    });
    settings.configure({ lm });

    const rlm = new RLM('question: str, context: str -> answer: str', {
      handlers: [searchHandler],
    });
    const result = await rlm.aforward({
      question: 'Where is the needle?',
      context: LONG_CONTEXT,
    });

    expect(result.get('answer')).toContain('needle result for needle');
    expect(searchQueries).toEqual(['needle']);
    expect(lm.classifierCalls.length).toBe(1);
    // Oracle leaf made exactly two LM calls: one to request the
    // Search, one to produce the final value.
    expect(lm.oracleCalls.length).toBe(2);
    // Turn 1's prompt must include the effect block with the handler's
    // result — otherwise the LM could not have "seen" the search hit.
    expect(lm.oracleCalls[1]!.content).toContain('[[EFFECT turn=0 kind=Search]]');
    expect(lm.oracleCalls[1]!.content).toContain('result: needle result for needle');
  });

  it('reinjects WriteMemory writes into the next oracle turn system message', async () => {
    // Scenario: a single top-level oracle plan with a 1-field memory
    // schema. Turn 0 of the oracle's effect loop emits WriteMemory;
    // turn 1 observes the updated banner in its own system message,
    // then emits a value. The plan is user-supplied so the test
    // doesn't depend on the default `failure_diagnostic` fields — we
    // keep a single string field for clarity.
    const memorySchema: MemorySchema = {
      name: 'demo',
      fields: [
        {
          name: 'note',
          type: 'string',
          description: 'a scratch note',
          maxLength: 60,
        },
      ],
      maxBytesSerialized: 512,
    };
    const plan: StaticPlan = {
      taskType: 'pairwise',
      template: oracle(vref('input'), undefined),
      memorySchema,
    };

    const lm = new MemoryScriptedAsyncLM({
      classifierPayload: JSON.stringify({
        primary: 'pairwise',
        confidence: 0.95,
        candidates: ['pairwise'],
      }),
      initialEffect: {
        name: 'WriteMemory',
        args: { key: 'note', value: 'remembered' },
      },
      followUpAnswer: 'final answer with memory',
    });
    settings.configure({ lm });

    const rlm = new RLM('question: str -> answer: str', {
      taskType: 'pairwise',
      plans: [plan],
    });
    const result = await rlm.aforward({
      question: 'what should we remember?',
    });

    expect(result.get('answer')).toBe('final answer with memory');

    expect(lm.oracleCalls.length).toBe(2);
    const firstSystem = lm.oracleCalls[0]!.systemContent;
    const secondSystem = lm.oracleCalls[1]!.systemContent;
    // Turn 0 sees the empty banner (header/footer only); turn 1 sees
    // the written field rendered inside the banner.
    expect(firstSystem).toContain('[[RLM_MEMORY schema=demo]]');
    expect(firstSystem).not.toContain('note: string =');
    expect(secondSystem).toContain('[[RLM_MEMORY schema=demo]]');
    expect(secondSystem).toContain('note: string = "remembered"');
  });
});

/**
 * Async scripted LM: first oracle turn emits one effect JSON, later turns
 * return a terminal value (detects first turn via absence of `[[EFFECT` in
 * user content). Richer chains use `rlm_effects.test.ts`.
 */
class EffectScriptedAsyncLM extends BaseLM {
  readonly calls: Array<{ readonly role: 'classifier' | 'oracle'; readonly content: string }> = [];
  readonly classifierPayload: string;
  readonly initialEffect: { readonly name: string; readonly args: Readonly<Record<string, unknown>> };
  readonly followUpAnswer: string;

  constructor(options: {
    readonly classifierPayload: string;
    readonly initialEffect: { readonly name: string; readonly args: Readonly<Record<string, unknown>> };
    readonly followUpAnswer: string;
  }) {
    super({ model: 'effect-scripted-async' });
    this.classifierPayload = options.classifierPayload;
    this.initialEffect = options.initialEffect;
    this.followUpAnswer = options.followUpAnswer;
  }

  protected override async agenerate(
    _prompt?: string,
    messages?: readonly Message[],
    _kwargs?: Record<string, unknown>,
  ): Promise<readonly LMOutput[]> {
    await Promise.resolve();
    const userContent = extractUserContent(messages);
    const allContent = allMessageContent(messages);
    const isClassifier = allContent.includes('Classify the user request');
    this.calls.push({ role: isClassifier ? 'classifier' : 'oracle', content: userContent });
    if (isClassifier) return [this.classifierPayload];

    // Turn 0: raw prompt, no effect block yet -> emit the effect
    // request. Turn 1+: the prompt now contains an `[[EFFECT` block,
    // so we commit to the final answer.
    const firstEffectTurn = !userContent.includes('[[EFFECT');
    if (firstEffectTurn) {
      return [
        JSON.stringify({
          kind: 'effect',
          value: null,
          effect_name: this.initialEffect.name,
          effect_args: this.initialEffect.args,
        }),
      ];
    }
    return [
      formatOracleCompletion(
        allContent,
        userContent,
        this.followUpAnswer,
        new Map<string, boolean>(),
      ),
    ];
  }

  get oracleCalls(): readonly { readonly content: string }[] {
    return this.calls.filter((c) => c.role === 'oracle');
  }

  get classifierCalls(): readonly { readonly content: string }[] {
    return this.calls.filter((c) => c.role === 'classifier');
  }
}

/**
 * Like `EffectScriptedAsyncLM` but records system vs user content per oracle
 * call so memory-banner assertions can target the system message only.
 */
class MemoryScriptedAsyncLM extends BaseLM {
  readonly calls: Array<{
    readonly role: 'classifier' | 'oracle';
    readonly userContent: string;
    readonly systemContent: string;
  }> = [];
  readonly classifierPayload: string;
  readonly initialEffect: {
    readonly name: string;
    readonly args: Readonly<Record<string, unknown>>;
  };
  readonly followUpAnswer: string;

  constructor(options: {
    readonly classifierPayload: string;
    readonly initialEffect: {
      readonly name: string;
      readonly args: Readonly<Record<string, unknown>>;
    };
    readonly followUpAnswer: string;
  }) {
    super({ model: 'memory-scripted-async' });
    this.classifierPayload = options.classifierPayload;
    this.initialEffect = options.initialEffect;
    this.followUpAnswer = options.followUpAnswer;
  }

  protected override async agenerate(
    _prompt?: string,
    messages?: readonly Message[],
    _kwargs?: Record<string, unknown>,
  ): Promise<readonly LMOutput[]> {
    await Promise.resolve();
    const userContent = extractUserContent(messages);
    const allContent = allMessageContent(messages);
    const systemContent = extractSystemContent(messages);
    const isClassifier = allContent.includes('Classify the user request');
    this.calls.push({
      role: isClassifier ? 'classifier' : 'oracle',
      userContent,
      systemContent,
    });
    if (isClassifier) return [this.classifierPayload];

    const firstEffectTurn = !userContent.includes('[[EFFECT');
    if (firstEffectTurn) {
      return [
        JSON.stringify({
          kind: 'effect',
          value: null,
          effect_name: this.initialEffect.name,
          effect_args: this.initialEffect.args,
        }),
      ];
    }
    return [
      JSON.stringify({
        kind: 'value',
        value: this.followUpAnswer,
        effect_name: null,
        effect_args: null,
      }),
    ];
  }

  get oracleCalls(): readonly {
    readonly userContent: string;
    readonly systemContent: string;
  }[] {
    return this.calls.filter((c) => c.role === 'oracle');
  }
}

function extractSystemContent(
  messages: readonly Message[] | undefined,
): string {
  if (!messages) return '';
  for (const msg of messages) {
    if (msg.role !== 'system') continue;
    if (typeof msg.content === 'string') return msg.content;
    return msg.content
      .map((part) => (part.type === 'text' ? (part.text ?? '') : ''))
      .join('\n');
  }
  return '';
}
